name: Deploy Node.js Express API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the latest code from Git
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'


      # Install dependencies
      - name: Install dependencies
        run: npm install

     
      # Deploy to the Ubuntu server using scp
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          timeout: "200s"
          target: "~/image_resizer"

      # (Optional) Restart the Node.js process using SSH
      - name: Restart Application via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/image_resizer
            # Install production dependencies (if needed)
            npm install --production
            # Restart the app using PM2 (or start it if it isn’t running)
            pm2 reload image-api   || pm2 start server.js --name image-api  

